version: '3'

services:
  database-1:
    image: 'postgres:alpine3.20'
    container_name: posgresql-dev
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
#      TODO remove this on commit and push
      device: D:/Github/webflux-example/docker-compose/postgres/data